### ISSUE TITLE
Why use port 2048

### ISSUE THREAD

**Issue by kagol** [alexnm/react-ssr#11]
Under the macOS, port 2048 has been occupied by some system processes.
![image](https://user-images.githubusercontent.com/9566362/52028352-a86bfb00-2549-11e9-94b1-7ab2e753f999.png)

**Comment by alexnm** [comment]
No specific reason, picked a number at random. you can easily change the port here (https://github.com/alexnm/react-ssr/blob/a000e1161d2ae8a5d5843bea6599ebc62e6fd75f/src/server.js#L47) before running the example

**Comment by kagol** [comment]
Thanks
