### ISSUE TITLE
npm audit not working

### ISSUE THREAD

**Issue by morantj** [alexnm/react-ssr#12]
Hi there

I experienced some issue when trying to fix or even show the audit dependencies :
`$: npm audit`

this ends in : 
`$: npm ERR! code ENOAUDIT`
`$: npm ERR! audit Your configured registry (https://registry.npmjs.org/) does not support audit requests, or the audit endpoint is temporarily unavailable.`

This is the standard registry and it works for my other projects. I tried to remove the node_modules folder and re-run "npm install", but it still displaying the same error above.

When I remove the package-lock.json there's no audit error but "npm run dev" is now crashing and throws me this :
`TypeError: Cannot read property 'properties' of undefined
    at module.exports (/home/deptinfo/Documents/DEV/react-ssr/node_modules/webpack-cli/bin/config-yargs.js:89:48)
`

Does anyone have an idea on how to make "npm audit" great again ?

Thanks

**Comment by alexnm** [comment]
very strange error, not sure if it's related to the repo itself since I'm not getting it. What version of node/npm are you using?

**Comment by morantj** [comment]
I'm using 

node 10.15.1
npm 6.8.0

**EDIT :** 
So to be sure, I fully re-created my server's image (pm2, nginx, node, npm, etc.) and I finally have access to npm audit. This should surely be a problem with the installation of these packages. 

Sorry for inconvenience

BTW, it's a very helpful/educative project, thank you to share it

**Comment by alexnm** [comment]
thanks, any feedback is welcome!
