### ISSUE TITLE
Integrating the code with Css 

### ISSUE THREAD

**Issue by rahulrsingh09** [alexnm/react-ssr#16]
Hi @alexnm . This code has been really great in trying to understand React SSR.

But one paint point has been , I have been trying to get this setup work with a css file or module of react and i have searched a lot of blogs and hours of trying toi tweak webpack but nothing seem to work .

These are the following options i have explored.

 - https://www.npmjs.com/package/isomorphic-style-loader
 - https://cssinjs.org/server-side-rendering/?v=v10.0.0-alpha.22
 - webpack loaders

But in none the process is simple or clearly mentioned the one which i tried a lot was isomorphic loader which seemed promising but then it gave some vague errors after setting it in my css files `Unexpected token (1:0) You may need an appropriate loader to handle this file type.`

Can you please set some context on this it would be really helpful , i had seen . one closed issues on these lines but i tried but its difficult grasp the loader on the server side of things end

**Comment by alexnm** [comment]
Hi @rahulrsingh09. thanks for opening this. This is a rather old codebase so I'm not sure if things have changed in the meantime, I haven't configured webpack in a while now. You should have a look at css-loader and style-loader, those where the two plugins for webpack we were using in the past for css-modules. for scss, there's sass-loader as well, who is added on top.

**Comment by alexnm** [comment]
You should start from here - https://github.com/webpack-contrib/css-loader

**Comment by rahulrsingh09** [comment]
Hi @alexnm Thanks for getting back, i will certainly take a look at this, but ig i Remeber correctly i have already tried and added it to the code with the same error or some post loader error, but any ways i will try amd add it again and check

**Comment by alexnm** [comment]
@rahulrsingh09 check #17
