### ISSUE TITLE
how to keep the redux state in line with persisted redux state in the client

### ISSUE THREAD

**Issue by gwl002** [alexnm/react-ssr#18]
hello,@alexnm.Very nice work for learning ssr .But I am confused how to keep the redux-persist work with this template work.

**Comment by alexnm** [comment]
hey, sorry for the delay, for some reason I was not watching this repo.

I haven't worked with redux-persist, but I assume the setup should work on the server as well as on the client. You add the middleware and the provider around the rendered app (in the server file)
