### ISSUE TITLE
how do we pass the url params to serverFetch function

### ISSUE THREAD

**Issue by rajendrabadri123** [alexnm/react-ssr#20]
const dataRequirements =
                routes
                    // .filter( route => matchPath( req.url, route ) ) // filter matching paths
                    .map( route => route.component ) // map to components
                    .filter( comp => comp.serverFetch ) // check if components have data requirement
                    .map( comp => store.dispatch( comp.serverFetch() ) ); // dispatch data requirement

how do we pass the url params to serverFetch function, 
if i pass the node req.url, then i need to reload the page on every page, 
so when using the React Link, how do get the url Params in the componet serverFetch function.

**Comment by alexnm** [comment]
I think the matchPath function gives you all the details about the url (including the parameters), but I haven't worked with react ssr in a long time now, I might be wrong

**Comment by rajendrabadri123** [comment]
Okay thanks for update.

**Comment by javadmohammadis** [comment]
Please send me a sample code for this issue,
I can't solve this problem
