### ISSUE TITLE
how can get url params

### ISSUE THREAD

**Issue by javadmohammadis** [alexnm/react-ssr#21]
how can get url param in this rout?
http://localhost:2048/secret/:id

---- 
i can't get params in fetchData 

Secret.serverFetch = fetchData; // static declaration of data requirements

const mapStateToProps = ( state ) => ( {
    circuits: state.data,
} );

const mapDispatchToProps = {
    fetchData,
};

**Comment by alexnm** [comment]
check out the sample from the fetch data chapter here: https://www.freecodecamp.org/news/demystifying-reacts-server-side-render-de335d408fe4/#fetch-data

```javascript
const dataRequirements =
        routes
            .filter( route => matchPath( req.url, route ) ) // filter matching paths
            .map( route => route.component ) // map to components
            .filter( comp => comp.serverFetch ) // check if components have data requirement
            .map( comp => store.dispatch( comp.serverFetch( ) ) ); // dispatch data requirement
```

matchPath also gives you the route params: https://github.com/ReactTraining/react-router/blob/master/packages/react-router/docs/api/matchPath.md

you can pass the route params to the comp.serverFetch( ) call which is the call of the static data requirements from your component
