### ISSUE TITLE
how to access client-side rendering page

### ISSUE THREAD

**Issue by vladp** [alexnm/react-ssr#5]
Hello, thank you for making the example available.
I am trying to learn from it to understand how to create server and client side bundles from the same project.

I can see (and tested) the 

>     npm server
>     http://localhost:2048
pair
It is working well.

However, what port/URL do I access to get to the CSR (client side rendering) setup ?

thank you

**Comment by alexnm** [comment]
there's no separate static server for the client rendering, the existing node endpoint does both the static file serving and the ssr with react. I hope this answers your question

**Comment by vladp** [comment]
Thank you for the follow up.  When I access http://localhost:2048, it seems to do be serving the ssr, not the static (CSR side).


```
        <!DOCTYPE html>
        <html>
        <head>
            <meta charset="utf-8">
            <title data-react-helmet="true"></title>
            
            <title>React SSR</title>
        </head>
        
        <body>
...
       </body>
      </html>
```

 
with running `npm run dev`, I am still not clear, what port I should be accessing to see the Static (CSR) page.

**Comment by alexnm** [comment]
The two modes are not working in parallel. If you want just client render, you have to comment out the server route that does SSR. But then only the root `/` url will work, you need to create a separate route to handle client side redirects (to always render the empty index.html and let the client do the work)

However, you might have to comment out some other stuff in the code to not have errors, because the code assumes SSR is there.

**Comment by vladp** [comment]
ok, thank you. I misunderstood the  example. I thought it showed how to do SSR and CSR from same project/same code base.

**Comment by alexnm** [comment]
Is there a specific reason you would need that? The way I see it, if you have SSR it will always go through there

**Comment by vladp** [comment]
I have a CRA-based  app (using the build chain from Create-react-app, which builds a CSR (client side rendering site)) .  I am building a companion piece to it, and that piece I would like to be in SSR for faster initial load times.    

I would like both apps to share majority of React components (both UI and logic-centric components).
So in a way, it is almost like one app with 2 entry points, one a CSR-entry point the other is SSR.


Basically, i am looking for a way to have 'one project' with 2 build/deploy chains, one that  builds and deploys my site as CRS, and another as SSR (and with slightly different entry points for each).

Right now I ended up with 2 projects, one using Razzle (for SSR), and the other Create-react-app build chain (for Client Side render (CSR).

So I would like to make my Razzle setup to be able to create SSR and CSR,  such that I do not have to maintain Create-react-app based tool chain (as I am using rewire  in that project, to escape a number of 'jails'/'restrictions' setup by the CRA ).

**Comment by alexnm** [comment]
hmm, I think you can do that easily if you do some magic in the server files. You could, based on the build (env variable) conditionally add the route for server side rendering (in case of SSR) OR add a route for serving the static index.html (in case of CSR) and configure webpack dev server there

**Comment by vladp** [comment]
thank you.  yes, probably it could be done easily. I tried but was not successful. So I was looking for examples. of one project that did both 

(I thought razzle enabled that (as it opens 2 ports: say 3000 and 3001. However, going to 3001 appear to be only a port to serve the bundle for ssr, not as a separate fully featured CSR route.)
