### ISSUE TITLE
How do I integrate this with react-hot-loader?

### ISSUE THREAD

**Issue by stanleynguyen** [alexnm/react-ssr#6]
I have followed your code structure and style but struggling with integrate all this with `react-hot-loader`. Please advice me on this

**Comment by ayushnawani** [comment]
same here, can you please guide us.

**Comment by alexnm** [comment]
Sorry for missing this, I didn't have the notifications on for some reason. You should check the webpack docs on using webpack-dev-middleware: https://webpack.js.org/guides/development/#using-webpack-dev-middleware
