### ISSUE TITLE
cannot run in the browser

### ISSUE THREAD

**Issue by douglasvegas** [alexnm/react-ssr#7]
when I run `npm run dev`  the terminal output these infos below:

`(node:33459) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): FetchError: request to http://ergast.com/api/f1/2018/circuits.json failed, reason: getaddrinfo ENOTFOUND ergast.com ergast.com:80
(node:33459) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:33459) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): FetchError: request to http://ergast.com/api/f1/2018/circuits.json failed, reason: getaddrinfo ENOTFOUND ergast.com ergast.com:80
(node:33459) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 3): FetchError: request to http://ergast.com/api/f1/2018/circuits.json failed, reason: getaddrinfo ENOTFOUND ergast.com ergast.com:80
(node:33459) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 4): FetchError: request to http://ergast.com/api/f1/2018/circuits.json failed, reason: getaddrinfo ENOTFOUND ergast.com ergast.com:80
`

**Comment by icastillejogomez** [comment]
Without code we can't help you. Please send to this feed the code.

**Comment by douglasvegas** [comment]
@icastillejogomez I just run the Base example repo.

**Comment by icastillejogomez** [comment]
Are you installing the dependencies with `npm install`?

**Comment by douglasvegas** [comment]
@icastillejogomez sure,I do it step by step.

**Comment by alexnm** [comment]
@douglasvegas which version of node are you using?

might not be relevant, now I took a closer look at your stack trace. is this request working in the browser: http://ergast.com/api/f1/2018/circuits.json? this request is being done by the site before doing the server render to populate the store with data.
