### ISSUE TITLE
Integrate with css file

### ISSUE THREAD

**Issue by pu3antasyah** [alexnm/react-ssr#9]
while I use import some css it always show error tokens. It's clearly expect .css too as .js while try to compile. How to use import .css components?

**Comment by alexnm** [comment]
this repo is not built on create-react-app so it doesn't have the css loaders by default. You need to add the `style-loader` in the `webpack.config` file: https://webpack.js.org/loaders/style-loader/

**Comment by redraushan** [comment]
> this repo is not built on create-react-app so it doesn't have the css loaders by default. You need to add the `style-loader` in the `webpack.config` file: https://webpack.js.org/loaders/style-loader/

Hi @alexnm, agree with you, however, can we already have style-loader by default implemented? I believe loading styles is quite common or expected in any react boilerplate.

**Comment by alexnm** [comment]
@redraushan feel free to do a PR with the changes. just one note, this is not necessarily a boilerplate, but rather a simple example of getting SSR to work in a React app.

**Comment by redraushan** [comment]
>@redraushan feel free to do a PR with the changes. just one note, this is not necessarily a boilerplate, but rather a simple example of getting SSR to work in a React app.

@alexnm looks good, i’ll come up with a PR that will have `style-loader` and `css-loader`

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by ajayvarghese** [comment]
@alexnm PR for CSS integration. https://github.com/alexnm/react-ssr/pull/17
